#!/usr/bin/env bash
# scripts/bootstrap-opencode.sh — Escreve opencode.jsonc para OpenCode
#
# Três comportamentos, só três:
#
#   1. Config não existe            → escreve um novo, completo.
#   2. Config existe, com o par de markers exatos e o bloco gerenciado
#      já idêntico ao atual         → no-op, status 0. Comparação é só
#                                     leitura; nada é reescrito.
#   3. Qualquer outra coisa         → RECUSA, status 3, não escreve nada,
#                                     e explica o que fazer à mão.
#
# ESTE SCRIPT NUNCA REESCREVE UM ARQUIVO EXISTENTE. Nem parcialmente,
# nem "só a região gerenciada". Reescrever JSONC alheio em bash+node
# custou quatro rodadas e produziu quatro jeitos distintos de destruir
# config do usuário — vírgula faltando absorvendo chave manual, marker
# dentro de comentário, marker parecido aceito por prefixo, chave
# aninhada confundida com top-level. Os dois caminhos que não podem
# perder dado são os dois que não reescrevem: criar onde não há nada, e
# recusar. Não reintroduza reescrita aqui.
#
# Consequência assumida: quando o cortex muda de lugar, o bloco fica
# velho e o script RECUSA. O caminho suportado é apagar o arquivo e
# rodar de novo — guardando antes qualquer chave manual pra recolar
# acima do marker. Config velho é o defeito benigno original; config
# destruído não é.
#
# Markers (linhas exatas, sem indentação):
#   // >>> jarvis-managed (regenerated by bootstrap-opencode.sh)
#   // <<< jarvis-managed
#
# CONTRATO DE SEGURANÇA — nunca pior que não fazer nada:
#   - Três fases. FASE 1 decide todos os alvos e não escreve nada — nem
#     mkdir, nem mktemp, nem arquivo temporário. Recusar (3) só acontece
#     aqui, então "nada foi escrito" é verdade por construção.
#     FASE 2 faz stage e valida TODOS os alvos, sem publicar nenhum.
#     FASE 3 publica.
#   - A publicação é `command /bin/link` do stage pro alvo: link(2) falha
#     com EEXIST se algo aparecer no caminho entre a decisão e a escrita.
#     Quem garante "só cria se não existe" é o kernel, não um `[ ! -f ]`
#     anterior. `mv -n` foi descartado: sai 0 sem mover, sem sinal de erro.
#     `ln` foi descartado porque `ln ORIGEM DIR` significa "linkar DENTRO
#     de DIR": com um diretório no alvo ele SAI 0 tendo criado
#     <alvo>/<nome-do-stage>. `command` evita função/alias com o nome do
#     binário.
#   - Se a publicação falhar no meio de vários alvos, a mensagem diz
#     exatamente o que foi e o que não foi escrito. Não há rollback:
#     desfazer também pode falhar, e mentir sobre isso é pior que
#     relatar o estado real.
#   - Falha inesperada de qualquer comando vira status 1 (trap ERR), pra
#     que status alheio nunca se disfarce de código do contrato.
#
# Status de saída (contrato — install.sh depende dele):
#   0  sucesso (escreveu, ou já estava atualizado)
#   1  falha inesperada. NÃO garante que nada foi escrito: com mais de um
#      alvo, a publicação é sequencial e o primeiro pode ter sido criado
#      antes de o segundo falhar. A mensagem em stderr é a AUTORIDADE
#      sobre quais alvos existem — ela lista o que foi publicado, ou diz
#      que nada foi. Não inferir estado do status 1.
#   2  erro de uso (argumento desconhecido)
#   3  RECUSA deliberada: existe um config que este script não escreveu
#      ou que está desatualizado. Nada foi escrito — recusa só acontece
#      na FASE 1, antes de qualquer publicação. Exige ação manual.
#      `install.sh all` reporta SKIPPED e segue; `install.sh opencode`
#      falha.
#
# LIMITAÇÕES CONHECIDAS (medidas, não hipotéticas):
#   - Sem node no PATH o arquivo recém-escrito não é validado antes de ser
#     publicado. Ele é gerado inteiramente por este script, e um path de
#     cortex com caractere de controle é recusado antes de qualquer
#     escrita, então o resultado é válido por construção — mas a
#     conferência independente não roda.
#   - json_escape cobre \ " newline CR tab backspace e form feed; os
#     demais controles U+0001–U+001F são RECUSADOS no preflight em vez
#     de escapados.
#   - O bloco gerenciado é sempre LF.
#   - `trap cleanup EXIT` NÃO dispara em SIGINT/SIGTERM não capturados no
#     Bash 3.2, e as duas fases se comportam de formas DIFERENTES sob sinal:
#     Ctrl-C na FASE 2 pode deixar um `.opencode-jarvis-stage.*` no diretório
#     do config e nenhum config é alterado — a publicação ainda não começou.
#     Ctrl-C na FASE 3 pode chegar DEPOIS de um alvo já ter sido publicado:
#     o config existe e o sinal mata o shell antes de qualquer diagnóstico
#     da FASE 3. Sucesso é silencioso — não existe relatório final impresso
#     no caminho feliz —, então o que se perde é a chance de reportar a
#     falha, não um relatório que teria saído. Inspecione os alvos à mão.
#     O stage em si é inofensivo: o opencode só lê `opencode.jsonc`.
#     Correção, pra quem pegar: traps explícitos de INT/TERM/HUP que
#     limpam e re-emitem o sinal preservando o status (`trap - INT; kill
#     -INT $$`).
#   - Remover o arquivo de stage é cosmético e NUNCA fatal. Quando falha
#     (flag de imutabilidade, diretório append-only, corrida de unlink) o
#     script avisa em stderr e segue: o config já está publicado nesse
#     ponto — stage e alvo são o mesmo inode — e abortar transformaria uma
#     escrita concluída em falha e, com dois alvos, impediria a publicação
#     do segundo. Fica um `.opencode-jarvis-stage.*` pra trás, inofensivo.
#     Vale igual pro `trap cleanup EXIT`, ali como guarda: um `rm` que falha
#     dentro de um trap EXIT sob errexit dispara o trap ERR e SUBSTITUI o
#     status de saída do run (3 sairia como 1, e `install.sh all` abortaria
#     o que devia pular). Nenhum caminho atual chega nesse estado — toda
#     recusa acontece na FASE 1, antes do primeiro mktemp — mas o trap não
#     pode ter opinião sobre o status de quem o disparou.
#   - Caminho de alvo com componente `..` é RECUSADO (3), não normalizado:
#     `..` só é resolvido depois que `mkdir -p` cria o componente que
#     faltava, então dois alvos distintos agora viram o mesmo arquivo
#     depois. Normalizar exigiria re-derivar o caminho, que é justamente
#     como o newline final some. Mesma escolha do bootstrap irmão.
#   - Alvos SÃO deduplicados por identidade antes da FASE 1: pai
#     canonicalizado (symlink resolvido) mais basename, e pais que existem
#     são comparados com `-ef` — identidade de inode, que pega alias de
#     mount/firmlink que normalização de string não pega. Cobre
#     `--project` rodado de dentro de ~/.config/opencode. Antes disso o
#     segundo alvo dava EEXIST e o relatório dizia "não deu pra criar X" e
#     listava X como criado no mesmo parágrafo.
#   - O validador lê com readFileSync(path, 'utf8'), que substitui bytes
#     UTF-8 malformados por U+FFFD em silêncio. Um config cujo path
#     guardado contenha bytes não-UTF-8 pode validar como OK tendo sido
#     alterado na leitura — e sem node nem essa leitura acontece.
#   - A falha do link(2) não distingue a causa: EEXIST, permissão, sistema
#     de arquivos somente-leitura, EXDEV e componente ausente chegam com
#     o mesmo status. A mensagem por isso é genérica e não afirma causa
#     que não verificou.
#   - O modo do arquivo só é conferido no caminho que devolveria SUCESSO
#     com um config preexistente (bloco já atual): todos os outros já
#     recusam. Config atual com bit de grupo/outro ligado vira recusa (3)
#     pedindo `chmod 600`; o script NÃO faz o chmod sozinho.
#
# AMBIENTE HERDADO — a REGRA, não uma lista.
#
# Este script assume ser invocado de um shell cujo estado ambiente não é
# hostil. Alguns estados hostis foram encontrados e corrigidos — mas o motivo
# de terem sido corrigidos NÃO é que quebravam o script: é que ACONTECEM POR
# ACIDENTE. `CDPATH` num profile, um wrapper de `cd` exportado, `umask`
# restritivo, `noclobber`, `physical`. São coisas que gente real tem na
# própria config, e quebrar por causa delas é bug.
#
# TESTE PRA ENTRAR NO CONJUNTO CORRIGIDO:
#   "um usuário real plausivelmente tem isto no shell profile dele?"
#   E NÃO: "dá pra fazer isto quebrar o script?"
#
# Corrigido (ocorre por acidente):
#   - CDPATH        `local CDPATH=` — `cd` imprimia o diretório na captura
#   - wrapper de cd `builtin cd`/`builtin pwd`
#   - umask         `chmod 600` explícito — mktemp não garante modo
#   - noclobber     `>|` na escrita deliberada do stage
#   - physical      `cd -L`/`pwd -L` onde o código promete grafia lógica
#   - keyword       `set +o keyword` — não passa no teste acima, foi corrigido
#                   só porque custa uma linha; o teste decide o que se PROCURA
#
# FORA DE ESCOPO POR DECISÃO — não por ser indefensável:
#   opções importadas (`noexec`, `onecmd`, `verbose`, `xtrace`/`PS4`),
#   descritores de arquivo fechados ou redirecionados, disposição de sinais,
#   limites de recurso, diretório inicial inesperado, `BASH_ENV`/`ENV`, `PATH`.
#
#   `onecmd` e `noexec` fazem o script sair 0 sem executar nada — o contrato
#   de sucesso mente — e NENHUM dos dois é corrigível daqui: com `onecmd` o
#   shell sai depois de um comando, qualquer que seja, inclusive um
#   `set +o onecmd` na primeira linha (medido, todas as formas). `verbose`
#   vaza o código pro stderr, igual `xtrace`. Com stderr fechado uma recusa 3
#   vira 1; com stdout fechado o `install.sh all` aborta.
#
#   O motivo de parar aqui: um ambiente adversário o bastante pra arranjar
#   isso é adversário o bastante pra trocar este script inteiro, e não existe
#   fronteira de privilégio aqui pra ele cruzar. Corrigir categoria por
#   categoria não tem fim natural e não compra nada contra esse modelo de
#   ameaça.
#
# COBERTURA REAL DO ENDURECIMENTO — chamadas SELECIONADAS, não todas.
# Foram endurecidas as que DECIDEM semântica ou publicam:
#   `link`, `mktemp`, `stat`, `rm`, `awk`, `tr`, `git`, `node`, `cd`, `pwd`.
# Seguem NUAS de propósito, porque não decidem nada: `mkdir -p`, `chmod`,
# `printf`, `echo`. Uma função com esses nomes muda o resultado? Muda — e
# quem consegue definir tal função também define `command` e `builtin`
# (verificado), então blindá-las não move a fronteira.
#
# Uso:
#   ./scripts/bootstrap-opencode.sh                # só global
#   ./scripts/bootstrap-opencode.sh --project      # também cria <cwd>/opencode.jsonc
#   HOME=/custom ./scripts/bootstrap-opencode.sh   # HOME custom
#   ./scripts/bootstrap-opencode.sh -h | --help    # ajuda
#
# Saída silenciosa em sucesso, com uma exceção: se a limpeza do arquivo de
# stage falhar depois de publicar, sai um aviso em stderr e o status continua 0
# — o config já está escrito (ver LIMITAÇÕES). Recusa e erro em stderr.

set +o keyword   # ver nota abaixo — precisa vir antes do modo estrito
# Primeiro comando executável de propósito: `set -Eeuo pipefail` ACRESCENTA
# opções e nunca limpa as que o bash importou de SHELLOPTS antes da linha 1.
# `keyword` faz `local d="$1"` virar atribuição de ambiente e derruba o
# script com variável não vinculada — medido. Uma linha resolve.
# `onecmd` NÃO é resolvível daqui: o shell sai depois de UM comando, seja
# qual for, inclusive este — medido em todas as formas. Ver AMBIENTE
# HERDADO: está fora de escopo por decisão, junto com `noexec`.

set -Eeuo pipefail

EXIT_FAILURE=1
EXIT_USAGE=2
EXIT_REFUSED=3

# Every claim about what happened is DERIVED from this list, never asserted.
# Two earlier versions of this script printed "nothing was written" while a
# config had already been installed; the sentence is now computed from a record
# of what was actually published.
PUBLISHED=""
written_note() {
  if [ -z "$PUBLISHED" ]; then
    printf 'No config was written.'
  else
    # "exist on disk", not "are in place": PUBLISHED records that link(2)
    # created each path, which stays true even on the one branch that then
    # fails to verify the result. A stronger claim would contradict that
    # branch's own message.
    printf 'These configs WERE CREATED by this run:%s. That records creation only — their state right now is NOT verified here, so check them. No other target was created.' "$PUBLISHED"
  fi
}

# Any command that trips errexit exits with ITS OWN status: an awk failing with
# 2 would look like a usage error, and one failing with 3 would be read by
# `install.sh all` as a safe refusal and skipped. Normalize every unexpected
# failure to 1 so only the branches below can produce 2 or 3. `set -E`
# propagates the trap into functions and subshells.
on_unexpected_error() {
  local status=$?
  echo "bootstrap-opencode: unexpected failure (command exited $status). $(written_note)" >&2
  exit "$EXIT_FAILURE"
}
trap on_unexpected_error ERR

# === Args ===
WRITE_PROJECT=0
for arg in "$@"; do
  case "$arg" in
    --project) WRITE_PROJECT=1 ;;
    -h|--help)
      # The leading comment block, whatever its length. A hardcoded line range
      # needed bumping on every header edit and silently either truncated the
      # help or started printing code. Line 1 is skipped only if it really is a
      # shebang; blank lines and indented comments are part of the header rather
      # than terminators, so neither truncates the output early.
      command awk 'NR == 1 && /^#!/ { next }
           /^[[:space:]]*#/ { print; next }
           /^[[:space:]]*$/ { print; next }
           { exit }' "$0"
      exit 0
      ;;
    *) echo "Argumento desconhecido: $arg" >&2; exit "$EXIT_USAGE" ;;
  esac
done

# === Newline-safe primitives ===
# `$( )` strips EVERY trailing newline, so any path captured through it can
# silently become a different path. Both helpers below return through a global
# instead. Same sentinel shape as read_link_exact in bootstrap-claude.sh and
# bootstrap-codex.sh; here the command emits its own terminating newline
# (pwd -P does), so exactly one is removed after the sentinel is stripped.
CAPTURED=""
capture_path() {
  CAPTURED="$("$@" && printf X)" || { CAPTURED=""; return 1; }
  CAPTURED="${CAPTURED%X}"
  CAPTURED="${CAPTURED%$'\n'}"
}

# Physical: every symlinked component resolved. Used ONLY for the --project
# guards, where two paths must be compared through whatever symlinks lie
# between them.
physical_path() {
  # `builtin cd`/`builtin pwd`, not the bare words: a shell FUNCTION named cd
  # made this script bake the wrong cortex root into the generated config
  # (measured), and an exported `cd` wrapper is a common shell-profile idiom,
  # so this is an ordinary-accident risk and not only an attack. `command cd`
  # would ALSO bypass such a function on Bash 3.2.57 — verified; `builtin` is
  # chosen because it names the builtin directly and reads unambiguously, not
  # because it is stronger. Neither is a trust boundary: a function named
  # `builtin` or `command` defeats both, and at that point nothing in-script
  # helps.
  #
  # `local CDPATH=` is not cosmetic. `cd` consults CDPATH and PRINTS the
  # directory it picked when it uses one, and that extra line lands inside the
  # sentinel capture — two lines where the caller requires exactly one. With
  # `CDPATH=.` merely exported, `scripts/install.sh --help` exited 1.
  local CDPATH=
  builtin cd -P -- "$1" 2>/dev/null && builtin pwd -P
}

# Logical: symlinked components kept as spelled. Used for the cortex root that
# goes INTO the generated config, so the paths written are the ones the user
# reached the cortex through — the same spelling every previous version wrote.
logical_path() {
  # `-L` explicitly: the `physical` shell option can be inherited through
  # SHELLOPTS before line 1, and `set -Eeuo pipefail` adds options without
  # clearing them. Measured: with it set, this function resolved symlinks and
  # the generated config named the cortex through /real/ instead of the /link/
  # the user actually invoked — contradicting the promise directly above.
  local CDPATH=
  builtin cd -L -- "$1" 2>/dev/null && builtin pwd -L
}

# Directory part by parameter expansion — $(dirname) has the same loss.
# Returns through DIR_OF.
DIR_OF=""
dir_of() {
  local d="$1"
  case "$d" in
    */*) d="${d%/*}"; [ -n "$d" ] || d=/ ;;
    *)   d=. ;;
  esac
  DIR_OF="$d"
}

# Quote a path for display. Every path this script prints is attacker-influenced
# in principle — a directory name can hold a newline or a terminal escape
# sequence, and the report whose entire job is to say exactly what was written
# must not be forgeable by the thing it is reporting on. `printf %q` renders a
# newline as $'\n' and an escape byte as $'\033'.
q() {
  printf '%q' "$1"
}

die() {
  echo "bootstrap-opencode: $1 $(written_note)" >&2
  exit "$EXIT_FAILURE"
}

# Deliberate refusal. Only ever reached in phase 1, before anything is
# published — the guard makes that structural rather than a convention, because
# the message says "Nothing was written" and that has to stay true.
refuse() {
  if [ -n "$PUBLISHED" ]; then
    die "internal: refused after publishing."
  fi
  printf '%s\n' "$1" >&2
  exit "$EXIT_REFUSED"
}

# `refuse "$(refusal_text ...)"` would swallow a failure inside refusal_text:
# the inherited ERR trap exits the subshell, and the outer refuse then prints
# an empty message and exits 3 anyway. Build the text first, check it, then
# refuse.
refuse_with_text() {
  local text
  text="$(refusal_text "$1" "$2" && printf X)" \
    || die "could not build the refusal message for $(q "$1")."
  text="${text%X}"
  text="${text%$'\n'}"
  [ -n "$text" ] || die "the refusal message for $(q "$1") came out empty."
  refuse "$text"
}

# === Paths ===
dir_of "${BASH_SOURCE[0]}"
capture_path logical_path "$DIR_OF" || die "cannot resolve the script directory"
SCRIPT_DIR="$CAPTURED"
capture_path logical_path "$SCRIPT_DIR/.." || die "cannot resolve the cortex root"
CORTEX_ROOT="$CAPTURED"
HOME="${HOME:-$(eval echo "~$(id -un 2>/dev/null || echo root)")}"
GLOBAL_DIR="$HOME/.config/opencode"
GLOBAL_CONFIG="$GLOBAL_DIR/opencode.jsonc"
# $PWD, not "$(pwd)".
PROJECT_CONFIG="$PWD/opencode.jsonc"

MARKER_START="// >>> jarvis-managed (regenerated by bootstrap-opencode.sh)"
MARKER_END="// <<< jarvis-managed"

# `type -P`, not `command -v`: `command -v` happily reports a shell FUNCTION
# named node and returns the bare word "node", which would then be invoked as a
# function and bypass validation entirely. `type -P` searches PATH only and
# yields an external pathname or nothing. The invocation site is additionally
# prefixed with `command`, because NODE_BIN can also arrive from the
# environment already pointing at a name a function could shadow.
# `( trap - ERR; … )` even though `|| true` is inside: the `command` quirk fires
# ERR for the failed lookup itself, the subshell dies, the assignment fails and
# the parent trap exits 1. Measured: with no node on PATH the script exited 1
# and wrote nothing, instead of taking the documented validation-free path.
NODE_BIN="${NODE_BIN:-$(trap - ERR; command type -P node 2>/dev/null || true)}"
# An env-supplied NODE_BIN may be a BARE NAME. `have_node` tests `[ -x "$NODE_BIN" ]`,
# and `[ -x node ]` resolves CWD-relative — so `NODE_BIN=node` would skip
# validation entirely on a machine that has a perfectly good node on PATH, or
# worse, run whatever ./node happens to be. Anything without a slash is resolved
# to an absolute path here; anything with one is the caller's explicit choice.
case "$NODE_BIN" in
  ''|*/*) ;;
  *) NODE_BIN="$(trap - ERR; command type -P "$NODE_BIN" 2>/dev/null || true)" ;;
esac

# Absolute and NOT taken from PATH: the create-only guarantee rests entirely on
# this being link(2), so it must not be resolvable to a shell function, an alias
# or a `ln` shim. Deliberately not overridable by the environment for the same
# reason — see the phase 3 comment for why `ln` cannot be used here.
LINK_BIN=/bin/link

# Removing a stage is cosmetic bookkeeping and is NEVER part of the contract. By
# the time it runs the file has either been published — stage and target are the
# same inode, so the config exists and is complete — or it is a leftover from a
# run that is already failing for its own, better reason. So a failed unlink must
# not change the exit status. It must not be silent either: `rm -f ... || true`
# gets the first half right and the second half wrong, reporting nothing while
# leaving a file behind. rm's own diagnostic stays on stderr; this adds the
# context and the fact that the leftover is harmless.
# BASH 3.2 TRAP, measured, and the reason EVERY `command …` call in this file
# that has an `|| handler` is wrapped in `( trap - ERR; … )`:
#
#   with `set -E` and an ERR trap installed, `command foo || handler` FIRES THE
#   ERR TRAP even though the failure is the left operand of `||`, which a bare
#   `foo || handler` does not. Our trap EXITS, so the handler NEVER RUNS.
#
# Holds for builtins and external binaries alike. A redirection on the call does
# NOT prevent this — it only swallows the trap's own message, which is strictly
# worse: `command foo 2>/dev/null || die` produced a completely SILENT exit 1
# with no diagnostic at all. An earlier round measured this backwards using a
# probe whose ERR trap only echoed instead of exiting, and concluded the
# redirect was a suppressor; it is not. Resetting ERR inside a subshell is the
# only form verified to reach the handler, and it keeps stderr intact.
#
# `|| :` on the emission, and an unconditional `return 0`. Without both, the
# warning itself can end the run: with stderr closed the write fails, errexit
# fires ERR, and that was measured to stop a two-target run after the first
# publication — a warning about a harmless leftover taking down the target that
# had not been published yet. Nothing on this path may be able to fail.
warn_stage_left() {
  printf 'bootstrap-opencode: warning: could not remove the staging file %s. It is harmless — opencode reads only opencode.jsonc — and can be deleted by hand.\n' "$(q "$1")" >&2 || :
  return 0
}

# Only ever holds paths this run reserved with mktemp. A slot is cleared once
# its stage has been published (the file then belongs to the target).
STAGE_COUNT=0
STAGE_PATHS=()
cleanup() {
  local k=0 leftover
  while [ "$k" -lt "$STAGE_COUNT" ]; do
    leftover="${STAGE_PATHS[$k]:-}"
    # `|| warn`, not a bare `rm`. The mechanism being guarded against is real
    # and was measured in isolation: under errexit, a failing rm inside an EXIT
    # trap fires the ERR trap, and the resulting `exit 1` REPLACES the status
    # the run was exiting with — a deliberate 3 comes out as 1, which
    # `install.sh all` aborts on where it would have skipped.
    # No current call path reaches that: every `refuse` runs in phase 1, before
    # the first mktemp, so a live stage never coexists with exit 3, and the
    # paths that do exit here with a stage are already exiting 1. This is a
    # guard, not a fix for an observed failure — it exists so that moving a
    # refusal after staging later cannot silently rewrite the exit status.
    if [ -n "$leftover" ]; then
      ( trap - ERR; command rm -f "$leftover" ) || warn_stage_left "$leftover"
    fi
    k=$((k + 1))
  done
  return 0
}
trap cleanup EXIT

# === Helpers ===

have_node() {
  [ -n "$NODE_BIN" ] && [ -x "$NODE_BIN" ]
}

# Escape a shell value for use inside a JSON string literal. The C0 controls
# NOT handled here are refused in preflight rather than smuggled through.
json_escape() {
  local s="$1"
  s="${s//\\/\\\\}"
  s="${s//\"/\\\"}"
  s="${s//$'\n'/\\n}"
  s="${s//$'\r'/\\r}"
  s="${s//$'\t'/\\t}"
  s="${s//$'\b'/\\b}"
  s="${s//$'\f'/\\f}"
  printf '%s' "$s"
}

# True when $1 holds a C0 control character json_escape does not cover, i.e.
# anything in U+0001–U+001F except \b \t \n \f \r. Such a byte would produce
# invalid JSON that, without node, would be installed and reported as success.
has_unescapable_control() {
  local stripped
  stripped="$(trap - ERR; printf '%s' "$1" | LC_ALL=C command tr -d '\001-\007\013\016-\037' && printf X)" \
    || die "cannot inspect a path for control characters"
  stripped="${stripped%X}"
  [ "$stripped" != "$1" ]
}

# === The managed block ===
# A variable, not a file: refusing must create nothing, and the block is needed
# to DECIDE (behaviour 2 compares against it) as well as to write.
build_managed_block() {
  local cortex home_j
  cortex="$(json_escape "$CORTEX_ROOT")"
  home_j="$(json_escape "$HOME")"
  MANAGED_BLOCK="$MARKER_START
  \"instructions\": [
    \"$cortex/BOOT.md\",
    \"$cortex/JARVIS.md\",
    \"$cortex/CLAUDE.md\",
    \"$cortex/RTK-codex.md\",
    \"$cortex/active/rules/inviolaveis.md\",
    \"$cortex/active/rules/padrao.md\"
  ],
  \"skills\": {
    \"paths\": [
      \"$cortex/active/skills\",
      \"$cortex/codex/agent-skills\",
      \"$cortex/codex/skills-local\",
      \"$home_j/.claude/skills\",
      \"$home_j/.codex/skills\"
    ]
  },
  \"mcp\": {
    \"playwright\": {
      \"type\": \"local\",
      \"command\": [\"npx\", \"@playwright/mcp@0.0.68\"]
    },
    \"graphify-brain\": {
      \"type\": \"local\",
      \"command\": [\"bash\", \"-lc\", \"exec graphify-mcp --graph \\\"\${JARVIS_BRAIN_HOME:-\$HOME/.jarvis/brain}/graphify-out/graph.json\\\"\"]
    },
    \"n8n\": {
      \"type\": \"local\",
      \"command\": [\"npx\", \"-y\", \"n8n-mcp-server@0.1.0\"]
    },
    \"MetaAds\": {
      \"type\": \"remote\",
      \"url\": \"https://mcp.facebook.com/ads\"
    }
  }
$MARKER_END"
}

# === Marker detection (read-only) ===
# EXACT whole-line equality, never a prefix match: `// >>> jarvis-managed-evil`
# is not a marker. Prints: ok | none | bad.
marker_state() {
  command awk -v start="$MARKER_START" -v end="$MARKER_END" '
    $0 == start { s++; if (s == 1) sl = NR; next }
    $0 == end   { e++; if (e == 1) el = NR; next }
    END {
      if (s == 0 && e == 0) { print "none"; exit }
      if (s == 1 && e == 1 && sl < el) { print "ok"; exit }
      print "bad"
    }
  ' "$1"
}

# The marker lines and everything between them, verbatim. Read-only.
MANAGED_REGION=""
extract_managed_region() {
  local out
  out="$(trap - ERR; command awk -v start="$MARKER_START" -v end="$MARKER_END" '
    $0 == start { inblk = 1 }
    inblk { print }
    inblk && $0 == end { exit }
  ' "$1" && printf X)" || return 1
  MANAGED_REGION="${out%X}"
  MANAGED_REGION="${MANAGED_REGION%$'\n'}"
}

# Octal permission bits of $1, through MODE_OF. BSD stat first, GNU second, so
# this works on macOS and on Linux. The result is fed to arithmetic, so it is
# validated as octal digits here rather than trusted — a surprising stat format
# would otherwise become an arithmetic error and surface as a bare status 1.
MODE_OF=""
target_mode() {
  local out
  # Each probe is captured and validated ON ITS OWN. Chaining them inside one
  # `$( )` with `||` is the catalogued stdout-preservation trap: the failed
  # probe's output is KEPT and the next probe's output is appended to it —
  # measured as "FSGARBAGE600" for a healthy 0600 file, which then failed the
  # octal check and turned a perfectly fine config into a bare status 1.
  #
  # A probe is discarded when it fails OR when it prints something that is not
  # an octal mode. Both matter: GNU `stat -f` is "filesystem status", so it can
  # succeed while printing a non-mode, and only the second test catches that.
  # `trap - ERR` INSIDE each subshell: a probe that fails is expected here, not
  # an unexpected failure, and `set -E` propagates the ERR trap into command
  # substitutions. Without this the trap runs in the subshell and prints
  # "unexpected failure (command exited 1). No config was written." on a run
  # that then succeeds and exits 0 — a false alarm on stderr. It cannot be
  # silenced with a redirection on the assignment: command substitution is
  # expanded before redirections are applied, so `2>/dev/null` there is too
  # late (verified).
  # `command stat`: a shell function named stat could report 600 for a
  # world-readable config and defeat the refusal below, which is the one check
  # standing between the user and a silently over-permissive config.
  out="$(trap - ERR; command stat -f '%Lp' "$1" 2>/dev/null)" || out=""
  case "$out" in ''|*[!0-7]*) out="" ;; esac
  if [ -z "$out" ]; then
    out="$(trap - ERR; command stat -c '%a' "$1" 2>/dev/null)" || out=""
    case "$out" in ''|*[!0-7]*) out="" ;; esac
  fi
  [ -n "$out" ] || die "cannot determine the permissions of $(q "$1")."
  MODE_OF="$out"
}

# === Refusal message ===
# Enough to act on without reading this script.
refusal_text() {
  local why="$2" target
  # Quoted for display like every other path that reaches output: a config
  # directory can hold a newline or a terminal escape, and this message is the
  # report. The quoted form is still copy-pasteable into a shell.
  target="$(q "$1")"
  # printf, NOT a heredoc. Bash implements `<<TXT` by creating a temporary file,
  # and this function runs in PHASE 1 — whose entire promise is that a refusal
  # follows no write of any kind, anywhere. A temp area that is full, read-only
  # or missing would turn a refusal (3) into an unexpected failure (1), and
  # `install.sh all` ABORTS on 1 where it SKIPS on 3, which is precisely the
  # distinction the exit contract exists to carry. Building the message in
  # memory removes the filesystem from the one path that must always be able to
  # say "Nothing was written".
  printf '%s\n' \
"bootstrap-opencode: refusing to modify $target" \
"  Reason: $why" \
"  Nothing was written. This script never rewrites an existing config — it only" \
"  creates one where there is none, or leaves an already-current one alone." \
"" \
"  The supported way to get a current config:" \
"" \
"    1. Open $target and copy out every key you added yourself" \
"       (theme, provider, keybinds, \$schema, model, ...). They will not survive" \
"       step 2." \
"    2. Delete the file." \
"    3. Re-run this script. It writes a fresh config containing the" \
"       jarvis-managed block:" \
"" \
"$MARKER_START" \
"       ... instructions / skills / mcp ..." \
"$MARKER_END" \
"" \
"    4. Paste your own keys back in, ABOVE the line" \
"" \
"$MARKER_START" \
"" \
"       and make sure the last one ends with a comma. Everything above that line" \
"       is yours and is never touched; the script only ever compares the block" \
"       from that line down." \
"" \
"  If you would rather keep this file as it is, that is fine — opencode will go" \
"  on using it. It simply will not be updated by this script."
}

# === Preflight ===
# Decides for one target and writes nothing. Sets PLAN to: fresh | current
#
# A global, not stdout: `refuse` exits 3, and inside a `$( )` that would end
# only the subshell — the failed assignment would then trip the ERR trap and
# the refusal would surface as 1.
PLAN=""
preflight_target() {
  local target="$1" state

  # A symlink is refused rather than resolved or replaced: renaming over it
  # would silently detach a dotfiles setup, and following it would write
  # somewhere the caller never named.
  if [ -L "$target" ]; then
    refuse "bootstrap-opencode: refusing to touch $(q "$target")
  Reason: it is a symlink, and this script will neither write through one nor
  replace it. Nothing was written.
  Point it at a real file, or replace the link with a regular file, then
  re-run."
  fi
  if [ -e "$target" ] && [ ! -f "$target" ]; then
    refuse "bootstrap-opencode: refusing to touch $(q "$target")
  Reason: it is not a regular file. Nothing was written."
  fi

  if [ ! -f "$target" ]; then
    PLAN=fresh
    return 0
  fi

  state="$(trap - ERR; marker_state "$target")"
  case "$state" in
    ok) ;;
    none) refuse_with_text "$target" "it has no jarvis-managed marker pair, so it was not written by this script" ;;
    *)    refuse_with_text "$target" "its jarvis-managed markers are malformed — there must be exactly one start line and one end line, the start first, each on its own line with no indentation" ;;
  esac

  extract_managed_region "$target" || die "cannot read $(q "$target")."
  if [ "$MANAGED_REGION" = "$MANAGED_BLOCK" ]; then
    # The ONLY branch that returns success for a file that already existed, so
    # it is the only place a permission problem can be reported as "all fine".
    # Every other outcome for an existing file already refuses. A fresh config
    # is chmod 600 by stage_fresh_config (mktemp alone would not guarantee it,
    # because umask is subtracted) and never reaches here.
    #
    # Refuse rather than chmod. This script does not mutate existing configs —
    # that is the whole create-or-refuse decision — and silently re-moding a
    # user's file is the same class of behaviour that decision removed. Telling
    # them is the fix; doing it behind their back is not.
    target_mode "$target"
    if [ "$((8#$MODE_OF & 8#077))" -ne 0 ]; then
      refuse "bootstrap-opencode: refusing to leave $(q "$target") as it is
  Reason: its jarvis-managed block is current, but the file is mode $MODE_OF —
  readable by group or other. An opencode config carries MCP definitions and
  local paths and should not be world-readable. Nothing was written.

  Fix it yourself, then re-run:

    chmod 600 $(q "$target")"
    fi
    PLAN=current
    return 0
  fi
  refuse_with_text "$target" "its jarvis-managed block is out of date — the cortex root moved, or the block itself changed"
}

# `--project` is only allowed where the file will not become an untracked
# addition to somebody's repository. Runs before any write.
preflight_project_location() {
  local dir="$1" project_phys cortex_phys rc probe git_bin

  capture_path physical_path "$dir" || die "cannot resolve project dir: $(q "$dir")."
  project_phys="$CAPTURED"
  capture_path physical_path "$CORTEX_ROOT" || die "cannot resolve cortex root: $(q "$CORTEX_ROOT")"
  cortex_phys="$CAPTURED"

  # A config written into the cortex checkout is an untracked file CI then
  # validates and a future commit may leak.
  if [ "$project_phys" = "$cortex_phys" ]; then
    refuse "bootstrap-opencode: refusing --project inside the cortex checkout ($(q "$cortex_phys")). Nothing was written."
  fi
  case "$project_phys/" in
    "$cortex_phys"/*)
      refuse "bootstrap-opencode: refusing --project inside the cortex checkout ($(q "$cortex_phys")). Nothing was written." ;;
  esac

  # --project is refused inside ANY git work tree, full stop. No tracking
  # check, no ignore check, no judgement about which repository states are
  # acceptable. Two separate holes lived in that interrogation — git
  # environment overrides pointing the tracking checks at a different
  # repository, and `-e "$probe/.git"` following a dangling symlink into a
  # broken one — and both existed only because the guard was trying to decide
  # WHEN writing into a repo is safe. It no longer decides. A user who really
  # wants a project config in a repository can create it themselves.
  # `command type -P`, not `command -v`: `command -v git` reports a FUNCTION
  # named git as "git" and would both pass this presence check and be the thing
  # invoked below. -P searches PATH only and yields an external pathname.
  # Same ERR-trap shape: without it, a machine with no git exits 1 here
  # instead of reaching the deliberate refusal two lines down.
  git_bin="$(trap - ERR; command type -P git 2>/dev/null || true)"
  if [ -z "$git_bin" ] || [ ! -x "$git_bin" ]; then
    refuse "bootstrap-opencode: refusing --project: git is not in PATH, so this script cannot tell whether $(q "$project_phys") is inside a repository. Nothing was written."
  fi

  # A redirected git view says nothing about the directory we are about to
  # write into, so there is nothing to trust here either.
  for probe in GIT_DIR GIT_WORK_TREE GIT_COMMON_DIR GIT_INDEX_FILE \
               GIT_OBJECT_DIRECTORY GIT_ALTERNATE_OBJECT_DIRECTORIES \
               GIT_CEILING_DIRECTORIES GIT_DISCOVERY_ACROSS_FILESYSTEM; do
    if [ -n "${!probe:-}" ]; then
      refuse "bootstrap-opencode: refusing --project: $probe is set, so git's view of $(q "$project_phys") is redirected and cannot be trusted. Nothing was written. Unset it and re-run."
    fi
  done

  # Any .git entry of ANY type — directory, file, symlink, dangling symlink —
  # in this directory or any ancestor. -L is tested first because -e follows a
  # link and a dangling one would slip past.
  probe="$project_phys"
  while : ; do
    if [ -L "$probe/.git" ] || [ -e "$probe/.git" ]; then
      refuse "bootstrap-opencode: refusing --project: $(q "$probe/.git") exists, so $(q "$project_phys") is inside a git repository. Nothing was written. Create the config there yourself if you want one."
    fi
    [ "$probe" = "/" ] && break
    dir_of "$probe"
    probe="$DIR_OF"
  done

  # git's own opinion, used for exactly one question: work tree, yes or no.
  # 0 means yes and is refused. 128 is the only accepted negative. Any other
  # status means git could not answer, and an unanswered question is a refusal.
  # There is deliberately no follow-up: the moment this asks "but is the file
  # tracked?" or "but is it ignored?" it is back to interpreting repository
  # state, which is where both of the previous holes lived.
  # `( trap - ERR; … )` is REQUIRED here, not stylistic: `command … || rc=$?`
  # fires the ERR trap under Bash 3.2 and on_unexpected_error would exit before
  # rc was ever assigned — and rc=128 ("not a repository") is the NORMAL path
  # for every project directory outside a repo, so without this the common case
  # would abort instead of proceeding.
  rc=0
  ( trap - ERR; command "$git_bin" -C "$dir" rev-parse --is-inside-work-tree >/dev/null 2>&1 ) || rc=$?
  case "$rc" in
    0)   refuse "bootstrap-opencode: refusing --project: $(q "$project_phys") is inside a git work tree. Nothing was written. Create the config there yourself if you want one." ;;
    128) return 0 ;;
    *)   refuse "bootstrap-opencode: refusing --project: 'git rev-parse' failed with status $rc in $(q "$project_phys"), so this script cannot tell whether that is inside a repository. Nothing was written." ;;
  esac
}

# === Validation of what we just generated ===
# Exit status is NOT the verdict: node exits 0 and prints exactly `OK`, or
# exits 0 and prints `REJECT: ...`. Any non-zero exit, any other output, is a
# failure. Nothing here can produce 3 — this runs after the decision phase, and
# a file this script generated being invalid is our problem, not the user's.
run_validator() {
  command "$NODE_BIN" - "$1" <<'NODE'
'use strict';
const fs = require('fs');
function verdict(v) { process.stdout.write(v); process.exit(0); }
let parsed;
try {
  // This file was generated by bootstrap-opencode.sh: the only comments in it
  // are the two full-line markers, so dropping full-line `//` is exact here.
  parsed = JSON.parse(fs.readFileSync(process.argv[2], 'utf8').replace(/^\s*\/\/.*$/gm, ''));
} catch (e) {
  verdict('REJECT: not valid JSON after dropping full-line // comments (' + e.message + ')');
}
if (!parsed || typeof parsed !== 'object' || Array.isArray(parsed)) {
  verdict('REJECT: top level is not a JSON object');
}
for (const key of ['instructions', 'skills', 'mcp']) {
  if (!Object.prototype.hasOwnProperty.call(parsed, key)) {
    verdict('REJECT: "' + key + '" missing from the top level');
  }
}
verdict('OK');
NODE
}

validate_generated() {
  local file="$1" out
  have_node || return 0
  out="$(trap - ERR; run_validator "$file" && printf X)" \
    || die "the validator did not run."
  out="${out%X}"
  # Whole-output equality: a lone matching line among other output is not a
  # verdict.
  [ "$out" = "OK" ] \
    || die "generated an opencode config that does not validate ($out)."
}

# === Phase 2: stage ===
# Writes the document beside its target and validates it. Publishes nothing.
stage_fresh_config() {
  local target="$1" slot="$2" stage
  dir_of "$target"
  mkdir -p "$DIR_OF"
  # mktemp creates the stage with O_EXCL, so the name cannot be raced, nothing
  # pre-existing is unlinked, and the redirection cannot follow a planted
  # symlink. Beside the target so publishing is a same-filesystem link(2).
  #
  # It does NOT guarantee 0600: mktemp opens 0600 but the kernel still subtracts
  # the umask, so `umask 0400` yields 0200 — a config its own owner cannot read,
  # published with exit 0. The existing mode guard does not catch it either: that
  # one refuses GROUP and OTHER bits, and 0200 has neither. It was built for the
  # too-permissive direction; this is the too-restrictive one. So the mode is
  # ASSERTED below rather than inherited.
  # `command mktemp` is the most load-bearing of these prefixes. A shell
  # function named mktemp could return an EXISTING pathname — the user's own
  # config, say — which the redirection below would then TRUNCATE. That turns a
  # script whose entire design is create-or-refuse into a silent destroyer, so
  # the name must resolve to the binary and nothing else.
  # `trap - ERR` so the failure is reported ONCE, by the outer trap, instead
  # of twice (subshell trap + parent trap) for a single mktemp failure.
  stage="$(trap - ERR; command mktemp "$DIR_OF/.opencode-jarvis-stage.XXXXXX")"
  STAGE_PATHS[$slot]="$stage"
  # Asserted, not inherited — see the mktemp note above. Done before the write
  # so the content never exists at a mode this script did not choose.
  chmod 600 "$stage"
  # `>|` and not `>`: `noclobber` can be inherited through SHELLOPTS before line
  # 1, and `set -Eeuo pipefail` ADDS options rather than clearing them, so a
  # plain `>` refuses to write to the file mktemp just made and the run dies
  # having created nothing. `>|` states the intent — this redirection is
  # deliberate and the target is ours.
  printf '{\n%s\n}\n' "$MANAGED_BLOCK" >| "$stage"
  validate_generated "$stage"
}

# === Phase 3: publish ===
# link(2) is the whole point: it fails with EEXIST if anything now occupies the
# target — a file, a symlink, a dangling symlink, a directory, a hard link — so
# the "only if absent" precondition is enforced by the kernel at the instant of
# the write, not by a `[ ! -f ]` some milliseconds earlier. It does not follow a
# symlink at the target either.
#
# `link(1)`, NOT `ln(1)`. This is the same trap that got relink_atomically
# deleted from this repo: BSD/macOS `ln SRC DIR` means "link INSIDE DIR", so if
# a directory appeared at the target between the phase-1 check and here, `ln`
# SUCCEEDED having created <target>/<stage-name> — measured, 1606 bytes on disk
# — while the run reported "No config was written". A phase-1 refusal of
# non-regular targets cannot close that: the check is phase 1 and the write is
# phase 3, and that TOCTOU window is the entire reason this design uses a hard
# link. /bin/link's two-operand form calls link(2) with none of ln(1)'s
# directory special-casing; verified to fail EEXIST for a directory, a regular
# file, a symlink to either, and a dangling symlink.
publish_stage() {
  # Separate statements: within a single `local`, the right-hand sides are
  # expanded before the earlier names in the same statement are in scope.
  local target="$1" slot="$2" stage shown
  stage="${STAGE_PATHS[$slot]}"
  # Quoted once, up front: the record below has to be a plain assignment that
  # cannot itself fail, so nothing fallible may sit between the verification
  # and the record.
  shown="$(q "$target")"
  # Cause-neutral. EEXIST, permissions, a read-only filesystem, EXDEV, a
  # missing path component, quota, link limits and I/O errors all arrive here
  # with the same status, and this file has spent six rounds learning not to
  # name a cause it did not verify.
  # `command` is not decoration. Bash 3.2 accepts `function /bin/link { ... }`
  # — the POSIX `"/bin/link"()` form is rejected, the keyword form is not — and
  # function lookup precedes the filesystem, so a shim by that exact name would
  # be called here while `[ -x "$LINK_BIN" ]` still passed. That hands the
  # directory-following leak back through the front door. `command` skips
  # function and alias lookup and runs the binary.
  # `( trap - ERR; … )`, exactly as for rm. An earlier round annotated the
  # `2>/dev/null` here as suppressing the spurious ERR trap; that was WRONG and
  # measured wrong, because the probe used an ERR trap that only echoed. With
  # the real trap, which EXITS, `command … 2>/dev/null || die` fires ERR,
  # on_unexpected_error terminates the shell, and `die` is NEVER REACHED — the
  # redirect merely swallowed the trap's own message, so a failing link(2)
  # produced a completely silent exit 1 with no publication note at all.
  ( trap - ERR; command "$LINK_BIN" "$stage" "$target" 2>/dev/null ) || die \
    "could not create $shown."
  # link(2) has returned success, so the target EXISTS, created by this run, at
  # exactly this path. That is the instant the statement becomes true, so it is
  # recorded here — before the verification below, which can fail. Recording
  # after a fallible step is how the report came to claim "No config was
  # written" about a file that existed.
  PUBLISHED="$PUBLISHED $shown"
  # Belt and braces. With link(2) this should be unreachable — it either creates
  # the exact path or fails. If it ever fires, the file WAS created and
  # something changed it since; the note above already lists it as written, so
  # this message no longer has to contradict it.
  [ "$stage" -ef "$target" ] || die \
    "$shown no longer resolves to the staged file — something changed it during publication. Inspect it before re-running."
  # The slot is cleared BEFORE the unlink so the EXIT trap does not retry an
  # unlink that just failed and warn about the same file twice. Clearing is safe
  # either way: the stage and the target are two names for one inode, so
  # removing the stage name can never remove the config.
  STAGE_PATHS[$slot]=""
  # Best-effort, non-fatal — see warn_stage_left. The config is published and
  # verified by this point; aborting here would report a completed write as a
  # failure and, with two targets, stop the second from ever being published.
  ( trap - ERR; command rm -f "$stage" ) || warn_stage_left "$stage"
}

# === Apply ===
# Phase 1 decides for every target and writes nothing at all — no mkdir, no
# mktemp, no temp file. Phase 2 writes. A refusal in phase 1 therefore cannot
# follow a completed write, and nothing in phase 2 can return 3.
# Checked in phase 1, with everything else that must be true before a single
# byte is staged. Without link(2) this script cannot publish safely, and falling
# back to `ln` would silently reintroduce the directory-following hole, so the
# only honest options are refuse or publish — never "publish less carefully".
[ -x "$LINK_BIN" ] || refuse \
  "bootstrap-opencode: refusing to write: $LINK_BIN is missing or not executable, and this script will not fall back to 'ln' (it follows into a directory at the target instead of failing). Nothing was written."

has_unescapable_control "$CORTEX_ROOT" && refuse \
  "bootstrap-opencode: refusing to write: the cortex root path contains a control character this script will not put into JSON. Nothing was written. Move the cortex to a path without control characters."
has_unescapable_control "$HOME" && refuse \
  "bootstrap-opencode: refusing to write: \$HOME contains a control character this script will not put into JSON. Nothing was written."

build_managed_block

TARGETS=("$GLOBAL_CONFIG")
if [ "$WRITE_PROJECT" -eq 1 ]; then
  # dir_of "$PWD/opencode.jsonc" is $PWD, which necessarily exists, so no
  # directory has to be created before the location can be checked.
  dir_of "$PROJECT_CONFIG"
  preflight_project_location "$DIR_OF"
  TARGETS[1]="$PROJECT_CONFIG"
fi

# Collapse targets that are the SAME FILE spelled differently — running
# `--project` from inside ~/.config/opencode is the plain case, and a symlinked
# parent is the subtle one. Without this the first publish records the path and
# the second link(2) fails with EEXIST, producing a report that simultaneously
# says "could not create X; it was not written" and lists X as created, then
# exits 1. Nothing was ever at risk of being overwritten — the kernel saw to
# that — but the REPORT contradicted itself, which is the defect this file
# exists to eliminate.
#
# `..` is REJECTED, not normalized. An earlier version claimed a non-existent
# parent could not collide with an existing one "because they would be the same
# directory". That is false through `..`: with HOME=/base/missing/.. and a
# project parent of /base/.config/opencode, the literal and canonical keys
# DIFFER at this point, both targets survive, and then `mkdir -p` CREATES
# `missing` — after which both paths resolve to the same file and the
# contradictory report comes straight back. Measured, exactly that.
#
# Normalizing `..` would mean re-deriving the path, which is how the trailing
# newline gets truncated; rejecting costs nothing because no legitimate caller
# needs it. The sibling bootstrap reached the same conclusion for the same
# class, so this file does not invent a second answer to one problem.
#
# Identity for the survivors is inode-based where it can be: two parents that
# both exist are compared with `-ef`, which is real directory identity and
# catches mount aliases and firmlinks that no amount of string canonicalisation
# would. Only when a parent does not exist yet does this fall back to the
# canonical string. With `..` gone that is sound ASSUMING NO CONCURRENT
# NAMESPACE CHANGE: `mkdir -p` creates directories and never symlinks, so this
# run cannot turn a non-resolving path into one that lands on an existing
# directory. It is NOT airtight against another process planting a symlink
# between this comparison and the mkdir. If that happens dedup can miss and two
# targets survive — but the OUTCOME stays safe anyway, because publication is
# create-only through link(2): the second target fails with EEXIST, nothing is
# overwritten, and the report names exactly what was created. The residue is a
# failed run, not a damaged config.
i=0
while [ "$i" -lt "${#TARGETS[@]}" ]; do
  case "/${TARGETS[$i]}/" in
    */../*)
      refuse "bootstrap-opencode: refusing to write: the target path $(q "${TARGETS[$i]}") contains a '..' component.
  Reason: '..' is resolved by the kernel only after any missing directory is
  created, so two targets that look different now can become the same file
  later. Nothing was written.
  Re-run with paths that contain no '..' (for the global config, set HOME to
  its resolved form)." ;;
  esac
  i=$((i + 1))
done

DEDUP_TARGETS=()
DEDUP_DIRS=()
DEDUP_BASES=()
i=0
while [ "$i" -lt "${#TARGETS[@]}" ]; do
  dedup_t="${TARGETS[$i]}"
  dedup_base="${dedup_t##*/}"
  dir_of "$dedup_t"
  # physical_path resolves symlinks; capture_path keeps a trailing newline.
  if capture_path physical_path "$DIR_OF"; then
    dedup_dir="$CAPTURED"
  else
    dedup_dir="$DIR_OF"
  fi
  dedup_seen=0
  j=0
  while [ "$j" -lt "${#DEDUP_DIRS[@]}" ]; do
    if [ "$dedup_base" = "${DEDUP_BASES[$j]}" ]; then
      if [ "$dedup_dir" = "${DEDUP_DIRS[$j]}" ]; then
        dedup_seen=1
      elif [ -d "$dedup_dir" ] && [ -d "${DEDUP_DIRS[$j]}" ] \
           && [ "$dedup_dir" -ef "${DEDUP_DIRS[$j]}" ]; then
        dedup_seen=1   # same inode reached by two different spellings
      fi
    fi
    j=$((j + 1))
  done
  if [ "$dedup_seen" -eq 0 ]; then
    DEDUP_DIRS[${#DEDUP_DIRS[@]}]="$dedup_dir"
    DEDUP_BASES[${#DEDUP_BASES[@]}]="$dedup_base"
    DEDUP_TARGETS[${#DEDUP_TARGETS[@]}]="$dedup_t"
  fi
  i=$((i + 1))
done
TARGETS=("${DEDUP_TARGETS[@]}")

STAGE_COUNT="${#TARGETS[@]}"
i=0
while [ "$i" -lt "$STAGE_COUNT" ]; do
  STAGE_PATHS[$i]=""
  i=$((i + 1))
done

# Phase 1 — decide everything, write nothing.
PLANS=()
i=0
while [ "$i" -lt "${#TARGETS[@]}" ]; do
  preflight_target "${TARGETS[$i]}"
  PLANS[$i]="$PLAN"
  i=$((i + 1))
done

# Phase 2 — stage and validate every target that needs writing. Still nothing
# published: a failure here leaves every config exactly as it was, and the
# stages are removed by the EXIT trap.
i=0
while [ "$i" -lt "${#TARGETS[@]}" ]; do
  case "${PLANS[$i]}" in
    fresh)   stage_fresh_config "${TARGETS[$i]}" "$i" ;;
    current) : ;;   # already up to date — the read-only comparison said so
    *)       die "internal: unknown plan '${PLANS[$i]}' for ${TARGETS[$i]}." ;;
  esac
  i=$((i + 1))
done

# Phase 3 — publish. Only now can a config appear, and only where the kernel
# confirms nothing else has taken the path.
i=0
while [ "$i" -lt "${#TARGETS[@]}" ]; do
  [ "${PLANS[$i]}" = fresh ] && publish_stage "${TARGETS[$i]}" "$i"
  i=$((i + 1))
done

exit 0
